  dtsen: {
    key: "dtsen",
    icon: "badge-help",
    title: "DTSen Desil 1–4",
    description: "Pendataan kondisi sosial ekonomi warga desil 1–4 untuk menentukan kebutuhan paling mendesak dalam perencanaan desa.",
    fields: [
      accessField("No"), accessField("NIK"), accessField("No KK"), accessField("Nama Warga"), accessField("Nama Kepala Keluarga"),
      {label:"Desil DTSen",name:"desil_dtsen",type:"select",options:["Desil 1 - Sangat miskin","Desil 2 - Miskin","Desil 3 - Rentan miskin","Desil 4 - Menuju rentan"],value:"Desil 1 - Sangat miskin"},
      accessField("Dusun"), accessField("RT"), accessField("RW"),
      {label:"Status Kepemilikan Rumah",name:"status_kepemilikan_rumah",type:"select",options:["Milik sendiri","Sewa/kontrak","Menumpang","Rumah dinas/lainnya"],value:"Milik sendiri"},
      {label:"Kondisi Rumah",name:"kondisi_rumah",type:"select",options:["Layak huni","Rusak ringan","Rusak sedang","Rusak berat/tidak layak huni"],value:"Layak huni"},
      {label:"Kualitas Lantai",name:"kualitas_lantai",type:"select",options:["Tanah/bambu","Semen","Ubin/keramik","Kayu/papan","Lainnya"],value:"Semen"},
      {label:"Kualitas Dinding",name:"kualitas_dinding",type:"select",options:["Bambu/kayu kualitas rendah","Tembok tanpa plester","Tembok diplester","Lainnya"],value:"Tembok diplester"},
      {label:"Sumber Air Minum",name:"sumber_air_minum",type:"select",options:["Air kemasan/isi ulang","Ledeng","Sumur terlindung","Sumur tidak terlindung","Mata air/sungai/air hujan"],value:"Sumur terlindung"},
      {label:"Sanitasi/Jamban",name:"sanitasi_jamban",type:"select",options:["Jamban sendiri layak","Jamban bersama","Jamban tidak layak","Tidak memiliki jamban"],value:"Jamban sendiri layak"},
      {label:"Sumber Penerangan",name:"sumber_penerangan",type:"select",options:["Listrik PLN","Listrik non-PLN","Bukan listrik"],value:"Listrik PLN"},
      {label:"Penyakit Kronis",name:"penyakit_kronis",type:"select",options:["Tidak ada","Ada, terkontrol","Ada, membutuhkan pengobatan rutin","Ada, belum tertangani"],value:"Tidak ada"},
      {label:"Disabilitas",name:"disabilitas",type:"select",options:["Tidak","Ya, ringan","Ya, sedang","Ya, berat"],value:"Tidak"},
      {label:"Jaminan Kesehatan",name:"jaminan_kesehatan",type:"select",options:["PBI JKN","JKN mandiri","Jaminan lain","Tidak memiliki"],value:"PBI JKN"},
      {label:"Pendidikan Terakhir",name:"pendidikan_terakhir",type:"select",options:["Tidak/belum sekolah","SD/sederajat","SMP/sederajat","SMA/sederajat","Diploma/Sarjana"],value:"Tidak/belum sekolah"},
      {label:"Status Pekerjaan",name:"status_pekerjaan",type:"select",options:["Tidak bekerja","Buruh harian","Petani/nelayan","Pekerja informal","Karyawan","Wirausaha"],value:"Tidak bekerja"},
      accessField("Penghasilan Rumah Tangga per Bulan"),
      {label:"Kepemilikan Usaha",name:"kepemilikan_usaha",type:"select",options:["Tidak memiliki","Usaha mikro","Usaha kecil","Usaha menengah"],value:"Tidak memiliki"},
      accessField("Aset Utama yang Dimiliki"), accessField("Bantuan Sosial yang Diterima"),
      {label:"Kebutuhan Mendesak",name:"kebutuhan_mendesak",type:"select",options:["Pangan/gizi","Perbaikan rumah","Air bersih/sanitasi","Pelayanan kesehatan","Pendidikan","Pekerjaan/pelatihan usaha","Perlindungan lansia/disabilitas","Bantuan sosial"],value:"Pangan/gizi"},
      {label:"Skor Urgensi",name:"skor_urgensi",type:"select",options:["1 - Rendah","2 - Cukup rendah","3 - Sedang","4 - Mendesak","5 - Sangat mendesak"],value:"3 - Sedang"},
      accessField("Usulan Intervensi", "textarea"),
      {label:"Status Verifikasi",name:"status_verifikasi",type:"select",options:["Belum diverifikasi","Terverifikasi desa","Perlu kunjungan ulang"],value:"Belum diverifikasi"},
      accessField("Tanggal Verifikasi", "date"), accessField("Petugas Verifikasi"), accessField("Keterangan", "textarea"),
    ],
  },
